language:
- php
- node_js
php:
- 7.1
before_install:
- wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
- unzip terraform_"$TF_VERSION"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$TF_VERSION"_linux_amd64.zip
- git config --global url."https://".insteadOf ssh://
- npm i -g npm@7
install:
- npm install
- composer install
script:
- composer install
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
cache:
  directories:
  - node_modules
  - vendor
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
jobs:
  include:
  - stage: deploy qa
    if: type IN (push) and branch = qa
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
    script:
    - terraform -chdir=provisioning/qa init -input=false
    - echo "Deploying to qa"
    - terraform -chdir=provisioning/qa apply -auto-approve -input=false
  - stage: deploy production
    if: type IN (push) and branch = main
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
    script:
    - terraform -chdir=provisioning/production init -input=false
    - echo "Deploying to production"
    - terraform -chdir=provisioning/production apply -auto-approve -input=false
env:
  global:
  - TF_VERSION=1.0.11
  - secure: kLbc1lzlS3fkKk+JxfsZKhMyrmW7Tn4ElOPVxI/nLte9/Vc9Sa3Ef2c+miC8pJVYSxNoOX7LMkPTKAFOvCCBNhHtc5OKL3B7j97UAQBLbJEOMnlnZ/bnkH068mXdABI1B9pxkqE3MEKfpJzcRh8PN2LNpyNzuwBd0PWa0QyQHIft77hO+xSIKILYFUw885Cbfo+SEXLrxkRY0j27fQ+jlNt6wW3zqskqp5ocUIgLycx4i2ikip7Moiy3uZ7DdnvM8DL7wKdlzvA1osItMB5t+jHh3IaK0ZSDXw+9JMBnxT2473YeWoabu+jxXBFCAuqTfCdmJDXEkkwLQpMa7WljzKdIPAGnDPEKnFjWHQbbYCmy/FotiiuNbFCxq8gKxAO6NX4wNIQTtiwiiT1fRdEmYU5DMcSF/Q9QxltUSYovS/Diwk0OIdZG6jg4QgTLPAmY2pmxOcMt92PvYjbWzLEYZp+Lx0vsZhNMLYoCoGqPF3Ygwz7hRQynOBgjhQfBwu2WCnZAf7k0NvLvWDhaaK75uQLaHgIFO1ZoCd5zhcqJdFDCWGuZjqph4M7b+AYfQ1pfR0Kl5e+2LHFDZeHsVvNA/oOmihzIBqrGs41LZzFqwIbA+iu3v8LON9VLAoWxoNPhc6ISdWexZ8I6n7GtcrowEaF/m4ah/I+nZ66i+eWsPaU=
